name: Clone issue
on: 
  issues:
    types: [labeled]

jobs:
  clone_issue:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run clone issue script
        run: python scripts/clone_issue.py
        env:
          GITHUB_TOKEN: ${{ secrets.SSP_ACTION_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          SSP_PLUGINS: ${{ vars.SSP_PLUGINS }}
