name: Dev Activity Notifications

on:
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, reopened, review_requested, review_request_removed, edited]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare message content
        run: |
          echo "DESC=$(if [ -n '${{ github.event.issue.body }}' ]; then echo '**Description:** ${{ github.event.issue.body }}'; fi)" >> $GITHUB_ENV
          echo "COMM=$(if [ -n '${{ github.event.comment.body }}' ]; then echo '**Comment:** ${{ github.event.comment.body }}'; fi)" >> $GITHUB_ENV
      - name: Send Notification to Discord
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            **${{ github.event.issue.title || github.event.pull_request.title }}**
            [@${{ github.actor }}](https://github.com/${{ github.actor }})
            ${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.comment.html_url }}
            ${{ env.DESC }}
            ${{ env.COMM }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
