name: Dev Activity Notifications

on:
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, reopened, review_requested, review_request_removed, edited]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Discord
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            User: ${{ github.actor }}
            Title: ${{ github.event.issue.title || github.event.pull_request.title }}
            Link: ${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.comment.html_url }}
            Description/Comment: ${{ github.event.comment.body || github.event.issue.body || github.event.pull_request.body }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
