name: Label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label Issue
        uses: actions/checkout@v2
      - name: Run Labeling Script
        run: python scripts/label_issues.py
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_TOKEN: ${{ secrets.SSP_ACTION_TOKEN }}
          SSP_PLUGINS: ${{ vars.SSP_PLUGINS }}
